[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taidl-to"
version = "2.2"
description = "TAIDL-TO: Test Oracle Generator for Tensor Accelerator ISAs"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    {name = "ACT Compiler Team"},
]
readme = "README.md"
dependencies = [
    "taidl @ git+https://github.com/thomasbarrett/taidl.git@master",
]

[project.optional-dependencies]
runtime = ["numpy", "jax"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"taidl_to.templates" = ["*.txt"]
"taidl_to.generic" = ["*.py"]
"taidl_to.xla-debug" = ["*"]
